---
- name: update web servers
  hosts: web
  
  tasks:
   - name: directory create
     file:
        path: /home/centos/web
        state: directory


- name: update app servers
  hosts: app
  
  tasks:
   - name: directory create
     file:
        path: /home/centos/app
        state: directory
...



...
