---
- name: update web servers
  hosts: web
  
  tasks:
   - name: directory create
     file:
        path: /home/centos/web
        state: directory

   - name: copying file content
     copy:
        dest: /home/centos/web/web.conf
        content: My web app config

- name: update app servers
  hosts: app
  
  tasks:
   - name: directory create
     file:
        path: /home/centos/app
        state: directory

   - name: copying file content
     copy:
        dest: /home/centos/app/app.conf
        content: My App config
...

