---
  - name: ensure git is installed
    package:
      name: git
      state: present

  - name: ensure code is update from git repo
    git:
      repo: https://github.com/nareshreddy1238/ecomm.git
      dest: /var/www/html
...
